#pragma once

//#define USE_PRESMOOTHED_PARDISO
//#define USE_PURE_PARDISO
#define USE_PRESMOOTHED_MULTIGRID
//#define USE_PRESMOOTHED_GAUSS_SEIDEL
//#define USE_PURE_GAUSS_SEIDEL


#ifdef USE_PURE_PARDISO
#define USE_PARDISO
#endif

#ifdef USE_PRESMOOTHED_PARDISO
#define RECURSIVE_STRUCTURE_REQUIRED
#define USE_PARDISO
#endif

#ifdef USE_PRESMOOTHED_GAUSS_SEIDEL
#define RECURSIVE_STRUCTURE_REQUIRED
#endif

#ifdef USE_PRESMOOTHED_MULTIGRID
#define RECURSIVE_STRUCTURE_REQUIRED
#endif
