#pragma once

//#define USE_PARDISO
#define USE_PRESMOOTHED_MULTIGRID
#define USE_PRESMOOTHED_GAUSS_SEIDEL
#define USE_PURE_GAUSS_SEIDEL




#ifdef USE_PRESMOOTHED_GAUSS_SEIDEL
#define RECURSIVE_STRUCTURE_REQUIRED
#endif

#ifdef USE_PRESMOOTHED_MULTIGRID
#define RECURSIVE_STRUCTURE_REQUIRED
#endif